
name: Build and Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          export APP_SETTINGS=test
          python test.py


  
#      - name: Deploy Production
#        uses: appleboy/ssh-action@master
#        with:
#          password: ${{ secrets.DEPLOY_PASSWORD }}
#          host: ${{ secrets.DEPLOY_IP }}
#          username: ${{ secrets.DEPLOY_USER }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          # check this https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages
#          script: |
#            [[ ! -d cumplo ]] && git clone https://github.com/josehbez/cumplo.git
#            [[ -d cumplo ]] && cd cumplo; git pull
#            docker pull docker.pkg.github.com/josehbez/cumplo/cumplo:latest
#            docker-compose stop
#            docker rm webcumplo || true
#            docker-compose up -d
#            docker container  exec -t webcumplo python cumplo/manage.py migrate
