
name: Build and Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          export APP_SETTINGS=test
          python test.py
  
      - name: Deploy Production
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.DEPLOY_PASSWORD }}
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          port: 22
          script: |
            [[ ! -d cargamos ]] && git clone https://github.com/josehbez/cargamos.git
            [[ -d cargamos ]] && cd cargamos; git pull
            export APP_SETTINGS=production
            docker-compose -f /mnt/cargamos/docker-compose.yml stop || true
            docker rm cargamos || true
            docker-compose -f /mnt/cargamos/docker-compose.yml up --build -d
            docker container  exec -t cargamos python manage.py db upgrade
